### ISSUE TITLE
1+offset

### ISSUE THREAD

**Issue by tjlane** [slaclab/psgeom#21]
From O. Yefanov via email, Feb 22 2017:

4 TJ: the script that creates a .geom file from calibration puts
coffset=1+offset but it should be 0+offset, otherwise all panels are 1
meter further...

**Comment by tjlane** [comment]
@chuckie82 I believe this is resolved in the current GitHub master. I think we just need to mirror it into the current build. Do you agree?

**Comment by chuckie82** [comment]
I don't recall seeing 1+offset. So I would think we are ok.
